---
title: "A3 - Data Visualization and Applications "
output:
  pdf_document: default
author: 'Nhung Lam'
---

## Introduction

The incarcerations trends data set contains a mass amount of data. This data reports on difference racial groups, geographical locations, city types, total US jail populations and more. The variables I decided to focus on from this large data set was focused at the state level to compare racial groups/POC jail populations to White populations. I focused on the differences and trends over the years between the two populations. I also looked at the type of city and how it related to jail population size.

## Trends Over Time Charts

I have a total of three trends over time charts. My charts are line charts that look at the variables of total US jail population over time. My first trends over time chart shows the US Jail Population from 1970-2018. We can see that over the years, the total US jail population has been steadily increasing. My other two plots show the US jail population from 1970-2018 for White and Black populations. We can see from these two plots that the incarceration of White populations steadily increases but dips back down around year 2010 and has been decreasing. Meanwhile, looking at the Black population, we can see it's been increasing with no stagnation or drop offs. The purpose of these plots is to potentially show the disproportionate incarcerations of one racial group over another. 

##Variable Comparison Chart

I have two variable comparison charts. My first looks at the city type and total US jail population. The purpose of this chart is to see if there is a correlation/association with the city type: rural, small/mid,suburban, or urban has with the average US jail population. As expected urban has the largest US Jail population, where the city is the most dense, suggesting a higher average of jail populations. My second chart looks at the relationship of land area in square miles with total US jail population averages. The plot shows that it is positive/right skewed. Land areas less than 50,000 square miles tend to have higher US jail populations. There are some interesting outliers where the max land areas do not have much of a US jail population. Th highest average us jail population has a land area of 4058. This shows that there isn't much of a correlation between land area and average population but shows that generally land areas of 4058 square miles. 

#Map
I had multiple maps. The first map just shows the average total US jail population. We can see the light color blue represents states with the highests total us jail population. We can see California is very high which is expected because of how big the state/population is. We don't see any stand out trends immediately. The purpose of this map is to give a relative idea of the average US jail population. My second map combines all the POC racial groups for the average US jail populations. At first glance, the map is not as much different as the first map. But we know from our calculated values from before hand that California has the largest Latinx average jail population which is included in the POC racial groups. Without the context of the calculated values from before it would be harder to understand these maps because they look so similar. The third and final map shows the average US white jail population. We need to remember since on average the white population is much larger than POC. Which means the proportions are harders to see between groups. There are more states that are more light colored blue but it doesn't mean they are being disproportionately incarcerated. If we look back at the trends over time charts we can see that white population's incarcerations/populations have actually decreased but yet only one of the racial groups, Black racial groups is seen to increase almost exponentially. My purpose of these multiple maps is to show how similar yet difficult it is to differentiate the slight differences without other charts/calculated values to take into account. With all these calculated values/charts/maps together we can see how disproporitionately POC, especially Black populations are incarcerated although on the surface, it may seem that they are equally being incarcerated.  
